#########################################################
# FEEL FREE TO CHANGE VARIABLES WHEN TESTING!!! DELETE DATA PASE (BUTTON UNDER) FOR FRESH INSTANCE
# HAVE FUN! /OSKAR
#########################################################
DELETE http://localhost:5132/db


#########################################################
# AUTH / SESSION (Register, Login, Logout)
#########################################################

### Register (new user)
POST http://localhost:5132/register
Content-Type: application/json

{
  "email": "http_user1@resbyra.se",
  "password": "Password123!",
  "role": "admin"
}

### Login (as that user)
POST http://localhost:5132/login
Content-Type: application/json

{
  "email": "http_user1@resbyra.se",
  "password": "Password123!",
  "role": "admin"
}

### Login status (should return true assuming you logged in :))
GET http://localhost:5132/login

### Logout
DELETE http://localhost:5132/login


#########################################################
# USERS
#########################################################

### Users - Get all
GET http://localhost:5132/users

### Users - Get by id
GET http://localhost:5132/users/1


#########################################################
# COUNTRIES
#########################################################

### Countries - Get all
GET http://localhost:5132/countries

### Countries - Search
GET http://localhost:5132/countries/search?term=sw


#########################################################
# CITIES
#########################################################

### Cities - Get all
GET http://localhost:5132/cities

### Cities - Search
GET http://localhost:5132/cities/search?term=sto


#########################################################
# DESTINATIONS
#########################################################

### Destinations - Get all
GET http://localhost:5132/destinations

### Destinations - Search
GET http://localhost:5132/destinations/search?term=kallt


#########################################################
# BOOKINGS
#########################################################

### Bookings - Get all
GET http://localhost:5132/bookings

### Bookings - Search
GET http://localhost:5132/bookings/search?term=1


#########################################################
# HOTELS
#########################################################

### Hotels - Get all
GET http://localhost:5132/hotels

### Hotels - By destination
GET http://localhost:5132/hotels/by-destination/2

### Hotels - By destination
GET http://localhost:5132/hotels/search?term=Sakura


#########################################################
# ROOMS
#########################################################

### Rooms - Get all
GET http://localhost:5132/rooms

### Rooms - By hotel
GET http://localhost:5132/rooms/by-hotel/1


#########################################################
# ACTIVITIES
#########################################################

### Activities - Get all
GET http://localhost:5132/activities

### Activities - Search
GET http://localhost:5132/activities/search?term=mushroom


#########################################################
# AMENITIES
#########################################################

### Amenities - Get all
GET http://localhost:5132/amenities

### Amenities - Search
GET http://localhost:5132/amenities/search?term=wifi


#########################################################
# AMENITIES <-> HOTELS
#########################################################

### Get amenities for a hotel
GET http://localhost:5132/hotels/1/amenities

### Get hotels for an amenity
GET http://localhost:5132/amenities/1/hotels


#########################################################
# DESTINATIONS <-> ACTIVITIES 
#########################################################

### DestinationActivites - Alla aktiviteter för en destination
GET http://localhost:5132/destinations/1/activities

### DestinationActivites - Alla destinations som har en aktivitet
GET http://localhost:5132/activities/1/destinations


#########################################################
# PACKAGES
#########################################################

### Packages – Get all ready packages
GET http://localhost:5132/packages


### Packages – Get one package 
GET http://localhost:5132/packages/1


### Packages – Search
GET http://localhost:5132/packages/search?term=Tokyo


### Packages – Search without term (should give all)
GET http://localhost:5132/packages/search

#########################################################
# ADMIN-ONLY  (koppla/ta bort)
#########################################################

### Link activity to destination (admin)
POST http://localhost:5132/destinations/activities/link
Content-Type: application/json

{
  "destinationId": 1,
  "activityId": 4
}

### Unlink activity from destination (admin)
DELETE http://localhost:5132/destinations/1/activities/1


### Travelers – Get all
GET http://localhost:5132/travelers


### Travelers – Create traveler (admin required)
POST http://localhost:5132/travelers
Content-Type: application/json

{
  "firstName": "Oskar",
  "lastName": "Gyllenör",
  "passportNumber": "P12345678",
  "age": 24,
  "bookingId": 1,
  "userId": 1
}

### Bookings – Get all
GET http://localhost:5132/bookings


### Bookings – Search (try empty + non-empty)
GET http://localhost:5132/bookings/search?term=1

### BookingRooms – Get all
GET http://localhost:5132/booking-rooms


### BookingRooms – Get by id
GET http://localhost:5132/bookroom/1

# FEATURE: PACKAGE <-> ACTIVITIES
#########################################################

### PackageActivities – Get activities for a package
GET http://localhost:5132/packages/1/activities

### PackageActivities – Link activity to package (ADMIN)
POST http://localhost:5132/packages/activities/link
Content-Type: application/json

{
  "packageId": 2,
  "activityId": 3
}


#########################################################
# FEATURE: CUSTOM CARDS
#########################################################

### CustomCards – Get all custom cards
GET http://localhost:5132/custom-cards

### CustomCards – Search custom cards by title
GET http://localhost:5132/custom-cards/search?term=trip


#########################################################
# FEATURE: CUSTOM CARDS <-> ACTIVITIES
#########################################################

### CustomCardsActivities – Get activities for a card
GET http://localhost:5132/custom-cards-activities/card/1

### CustomCardsActivities – Link activity to card (USER)
POST http://localhost:5132/custom-cards-activities
Content-Type: application/json

{
  "cardId": 1,
  "activityId": 2
}


#########################################################
# FEATURE: CUSTOM CARDS <-> hotels
#########################################################

### CustomCardsHotels – Get hotels for a card
http://localhost:5132/custom-cards-hotels/card/1

### CustomCardsHotels – Get cards for a hotel
GET http://localhost:5132/custom-cards-hotels/hotel/1


### CustomCardsHotels – Search hotels by cardId
GET http://localhost:5132/custom-cards-hotels/search?cardId=1


### LINK: link customCard 2 to hotel 2 (user)
POST http://localhost:5132/custom-cards/hotels/link
Content-Type: application/json

{
  "cardId": 1,
  "hotelId": 2
}

#########################################################
# FEATURE: CUSTOM CARDS <-> Rooms
#########################################################

### CustomCardsRooms – Get rooms for a card

GET http://localhost:5132/custom-cards-rooms/card/1
Content-Type: application/json


#########################################################
# FEATURE: CUSTOM CARDS <-> ROOMS
#########################################################

### CustomCardsRooms – Get rooms for a card
GET http://localhost:5132/custom-cards-rooms/card/1


### CustomCardsRooms – Get cards for a room
GET http://localhost:5132/custom-cards-rooms/room/1


### CustomCardsRooms – Search rooms by cardId
GET http://localhost:5132/custom-cards-rooms/search?cardId=1

#########################################################
# FILE 1: PackagesAmenities  (packages <-> amenities)
#########################################################

### GET: amenities for package 1 (seeded)
GET http://localhost:5132/packages/1/amenities

### LINK: link amenity 2 to package 2 (admin)
POST http://localhost:5132/packages/amenities/link
Content-Type: application/json

{
  "packageId": 2,
  "amenityId": 2
}

### UNLINK: remove that link again (admin)
DELETE http://localhost:5132/packages/2/amenities/2


#########################################################
# FILE 2: PackagesHotels  (packages <-> hotels)
#########################################################

### GET: hotels for package 1 (seeded)
GET http://localhost:5132/packages/1/hotels

### LINK: link hotel 2 to package 1 (admin)
POST http://localhost:5132/packages/hotels/link
Content-Type: application/json

{
  "packageId": 1,
  "hotelId": 2
}

### UNLINK: remove that link again (admin)
DELETE http://localhost:5132/packages/1/hotels/2


#########################################################
# FILE 3: PackagesRooms  (packages <-> rooms)
#########################################################

### GET: rooms for package 1 (seeded)
GET http://localhost:5132/packages/1/rooms

### LINK: link room 4 to package 4 (admin)
POST http://localhost:5132/packages/rooms/link
Content-Type: application/json

{
  "packageId": 4,
  "roomId": 4
}

### UNLINK: remove that link again (admin)
DELETE http://localhost:5132/packages/4/rooms/4